 export const BASE_URL = "/dashboard";

export const vehicleMakes = [
  { value: "Mercedes Benz", label: "Mercedes Benz" },
  { value: "Nissan", label: "Nissan" },
  { value: "Haojin", label: "Haojin" },
  { value: "Ford", label: "Ford" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Toyota", label: "Toyota" },
  { value: "YAMAHA", label: "YAMAHA" },
  { value: "Daihatsu", label: "Daihatsu" },
  { value: "Tata", label: "Tata" },
  { value: "Lexus", label: "Lexus" },
  { value: "Leyland", label: "Leyland" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "SHANGDONG LINGONG", label: "SHANGDONG LINGONG" },
  { value: "Mahindra", label: "Mahindra" },
  { value: "Porsche", label: "Porsche" },
  { value: "BMW", label: "BMW" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Volvo", label: "Volvo" },
  { value: "Jeep", label: "Jeep" },
  { value: "Audi", label: "Audi" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Range Rover", label: "Range Rover" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Subaru", label: "Subaru" },
  { value: "Honda", label: "Honda" },
  { value: "Mazda", label: "Mazda" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Mobius", label: "Mobius" },
  { value: "Peugeot", label: "Peugeot" },
];

export const expenseTypes = [
  { value: "Food", label: "Food" },
  { value: "Petty Cash", label: "Petty Cash" },
  { value: "Rent", label: "Rent" },
  { value: "Internet", label: "Internet" },
  { value: "Water", label: "Water" },
  { value: "Rider", label: "Rider" },
  { value: "Salaries", label: "Salaries" },
  { value: "Parking", label: "Parking" },
  { value: "Marketing", label: "Marketing" },
  { value: "Fuel", label: "Fuel" },
  { value: "Electricity", label: "Electricity" },
  { value: "Stationery", label: "Stationery" },
  { value: "Office Supplies", label: "Office Supplies" },
  { value: "Client Lunch", label: "Client Lunch" },
  { value: "Commission Payouts", label: "Commission Payouts" },
  { value: "Advances", label: "Advances" },
];
export const durations = [
  { value: "Monthly", label: "Monthly" },
  { value: "Annual", label: "Annual" },
 
];

export const insurancePartners = [
  { value: "AAR", label: "AAR" },
  { value: "Africa Merchant", label: "Africa Merchant" },
  { value: "AIG Kenya", label: "AIG Kenya" },
  { value: "APA", label: "APA" },
  { value: "Britam General", label: "Britam General" },
  { value: "Cannon General", label: "Cannon General" },
  { value: "CIC General", label: "CIC General" },
  { value: "Corporate", label: "Corporate" },
  { value: "Directline Assurance", label: "Directline Assurance" },
  { value: "Fidelity Shield", label: "Fidelity Shield" },
  { value: "First Assurance", label: "First Assurance" },
  { value: "GA", label: "GA" },
  { value: "Geminia", label: "Geminia" },
  { value: "ICEA LION General", label: "ICEA LION General" },
  { value: "Intra Africa Assurance", label: "Intra Africa Assurance" },
  { value: "Invesco Assurance", label: "Invesco Assurance" },
  { value: "Jubilee Allianz General", label: "Jubilee Allianz General" },
  { value: "Jubilee Health", label: "Jubilee Health" },
  { value: "Kenindia Assurance", label: "Kenindia Assurance" },
  { value: "Kenya Orient", label: "Kenya Orient" },
  { value: "Madison General", label: "Madison General" },
  { value: "Mayfair", label: "Mayfair" },
  { value: "MUA", label: "MUA" },
  { value: "Occidental", label: "Occidental" },
  { value: "Old Mutual", label: "Old Mutual " },
  { value: "Pacis", label: "Pacis" },
  { value: "Pioneer General", label: "Pioneer General" },
  { value: "Sanlam General", label: "Sanlam General" },
  { value: "Star Discover", label: "Star Discover" },
  { value: "Takaful of Africa", label: "Takaful of Africa" },
  { value: "Tausi Assurance", label: "Tausi Assurance" },
  { value: "The Heritage", label: "The Heritage" },
  { value: "The Kenyan Alliance", label: "The Kenyan Alliance" },
  { value: "The Monarch", label: "The Monarch" },
  { value: "Trident", label: "Trident" },
];

export const insuranceTypes = [
  { value: "Automobile Consultation", label: "Automobile Consultation" },
  {
    value: "Motor/Vehicle/Car Insurance",
    label: "Motor/Vehicle/Car Insurance",
  },
  { value: "Fire Insurance", label: "Fire Insurance" },
  {
    value: "Individual Medical Insurance",
    label: "Individual Medical Insurance",
  },
  {
    value: "Corporate Medical Insurance",
    label: "Corporate Medical Insurance",
  },
  { value: "Burglary/Theft Insurance", label: "Burglary/Theft Insurance" },
  { value: "Public Liability Insurance", label: "Public Liability Insurance" },
  {
    value: "Employers’ Liability (Work Injury Benefits Act - WIBA)",
    label: "Employers’ Liability (Work Injury Benefits Act - WIBA)",
  },
  { value: "Goods in Transit Insurance", label: "Goods in Transit Insurance" },
  { value: "Marine Insurance", label: "Marine Insurance" },
  { value: "Aviation Insurance", label: "Aviation Insurance" },
  {
    value: "Contractors’ All Risk Insurance",
    label: "Contractors’ All Risk Insurance",
  },
  {
    value: "Machinery Breakdown Insurance",
    label: "Machinery Breakdown Insurance",
  },
  {
    value: "Fidelity Guarantee Insurance",
    label: "Fidelity Guarantee Insurance",
  },
  {
    value: "Professional Indemnity Insurance",
    label: "Professional Indemnity Insurance",
  },
  { value: "Plate Glass Insurance", label: "Plate Glass Insurance" },
  { value: "Money Insurance", label: "Money Insurance" },
  {
    value: "Product Liability Insurance",
    label: "Product Liability Insurance",
  },
  {
    value: "Personal Accident Insurance",
    label: "Personal Accident Insurance",
  },
  {
    value: "Political Violence & Terrorism Insurance",
    label: "Political Violence & Terrorism Insurance",
  },
  { value: "Agricultural Insurance", label: "Agricultural Insurance" },
  {
    value: "Business Interruption Insurance",
    label: "Business Interruption Insurance",
  },
  { value: "Loss of Profits Insurance", label: "Loss of Profits Insurance" },
];

export const insuranceClasses=[
  { value: "Individual Cover", label: "Individual Cover" },
  { value: "Corporate Cover", label: "Corporate Cover" },
]
